name: Publish to PyPI (Trusted Publishing)

on:
  push:
    tags:
      - "v*"     # Runs when you push a tag like v0.1.0
  workflow_dispatch: # Allow manual trigger from Actions tab

permissions:
  contents: read
  id-token: write    # REQUIRED for OIDC authentication with PyPI

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # environment: pypi  # (optional) use if you later create an Actions environment named "pypi"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"   # Match your Jupyter/PyCharm Python

      - name: Upgrade pip and install build
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build source and wheel distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
